#!/usr/bin/env python3
"""
Lossless Migration Tool: SQLite to PostgreSQL
Migrates all tables, columns, constraints, sequences, and data from accl_lms.db into PostgreSQL accl_lms.
Performs 100% row count and data validation.
"""
import os
import sys
import sqlite3
import psycopg2
import psycopg2.extras

SQLITE_PATH = os.environ.get("SQLITE_PATH", "/data/admin/ACCLLMS/accl_lms.db")
PG_URL = os.environ.get("PG_URL", "postgresql://kishan_accl:HoodleLMS_Secure_2026@127.0.0.1:5432/accl_lms")

def get_sqlite_conn():
    conn = sqlite3.connect(SQLITE_PATH)
    conn.row_factory = sqlite3.Row
    return conn

def get_pg_conn():
    return psycopg2.connect(PG_URL)

def translate_type(sqlite_type):
    t = sqlite_type.upper().strip()
    if "INT" in t:
        return "BIGINT" if "QUOTA" in t or "SIZE" in t else "INTEGER"
    if "REAL" in t or "FLOAT" in t or "DOUBLE" in t:
        return "DOUBLE PRECISION"
    if "BLOB" in t:
        return "BYTEA"
    return "TEXT"

def migrate():
    print(f"[*] Connecting to SQLite database at {SQLITE_PATH}...")
    s_conn = get_sqlite_conn()
    s_cursor = s_conn.cursor()

    print(f"[*] Connecting to PostgreSQL database...")
    p_conn = get_pg_conn()
    p_conn.autocommit = False
    p_cursor = p_conn.cursor()

    # Get all tables in SQLite (excluding sqlite_sequence)
    s_cursor.execute("SELECT name, sql FROM sqlite_master WHERE type='table' AND name != 'sqlite_sequence' ORDER BY name;")
    tables = s_cursor.fetchall()

    print(f"[*] Found {len(tables)} tables to migrate.")

    # Disable foreign keys temporarily during data load in PostgreSQL
    p_cursor.execute("SET CONSTRAINTS ALL DEFERRED;")

    for tbl_row in tables:
        tbl = tbl_row["name"]
        sql = tbl_row["sql"]
        print(f"\n--- Migrating table: {tbl} ---")

        # Get table info from SQLite PRAGMA table_info
        s_cursor.execute(f'PRAGMA table_info("{tbl}");')
        cols = s_cursor.fetchall()
        
        # Build CREATE TABLE for Postgres
        col_defs = []
        pk_cols = []
        for col in cols:
            cid, cname, ctype, notnull, dflt_val, pk = col
            pg_type = translate_type(ctype)
            parts = [f'"{cname}"']
            
            if pk and len([c for c in cols if c["pk"]]) == 1 and "INT" in ctype.upper():
                parts.append("INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
            else:
                parts.append(pg_type)
                if notnull:
                    parts.append("NOT NULL")
                if dflt_val is not None:
                    # Clean SQLite default values
                    clean_dflt = dflt_val.strip()
                    if clean_dflt.upper() in ("NULL", "''", "0", "1"):
                        parts.append(f"DEFAULT {clean_dflt}")
                    elif clean_dflt.startswith("'") and clean_dflt.endswith("'"):
                        parts.append(f"DEFAULT {clean_dflt}")
                    else:
                        parts.append(f"DEFAULT '{clean_dflt}'")
                if pk:
                    pk_cols.append(f'"{cname}"')

        if pk_cols and not any("PRIMARY KEY" in p for p in col_defs):
            col_defs_str = ", ".join(col_defs) if col_defs else ""

        # Generate postgres DDL
        # Check if table already exists, drop if needed for fresh sync
        p_cursor.execute(f'DROP TABLE IF EXISTS "{tbl}" CASCADE;')
        
        # Build statement
        lines = []
        for col in cols:
            cid, cname, ctype, notnull, dflt_val, pk = col
            pg_type = translate_type(ctype)
            if pk and "INT" in ctype.upper() and len([c for c in cols if c["pk"]]) == 1:
                col_spec = f'"{cname}" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'
            else:
                col_spec = f'"{cname}" {pg_type}'
                if notnull:
                    col_spec += " NOT NULL"
                if dflt_val is not None:
                    clean_dflt = dflt_val.strip()
                    if clean_dflt.upper() == "NULL":
                        col_spec += " DEFAULT NULL"
                    elif clean_dflt.isdigit() or (clean_dflt.startswith('-') and clean_dflt[1:].isdigit()):
                        col_spec += f" DEFAULT {clean_dflt}"
                    elif clean_dflt.startswith("'") and clean_dflt.endswith("'"):
                        col_spec += f" DEFAULT {clean_dflt}"
                    else:
                        col_spec += f" DEFAULT '{clean_dflt}'"
            lines.append(col_spec)

        # Composite primary key if needed
        multi_pks = [c["name"] for c in cols if c["pk"]]
        if len(multi_pks) > 1:
            pks_str = ", ".join(f'"{c}"' for c in multi_pks)
            lines.append(f"PRIMARY KEY ({pks_str})")
        elif len(multi_pks) == 1 and "INT" not in cols[[c["pk"] for c in cols].index(1)]["type"].upper():
            lines.append(f'PRIMARY KEY ("{multi_pks[0]}")')

        # Add UNIQUE constraints from sqlite table DDL if present
        import re
        if "UNIQUE(" in sql.upper():
            unique_matches = re.findall(r'UNIQUE\s*\(([^)]+)\)', sql, re.IGNORECASE)
            for u in unique_matches:
                lines.append(f"UNIQUE ({u})")

        # Also extract inline UNIQUE column declarations (e.g. attendance_key TEXT UNIQUE NOT NULL)
        for s_line in sql.split('\n'):
            s_line_str = s_line.strip()
            if "UNIQUE" in s_line_str.upper() and not s_line_str.upper().startswith("UNIQUE"):
                m = re.search(r'^\s*"?([a-zA-Z0-9_]+)"?\s+.*UNIQUE', s_line_str, re.IGNORECASE)
                if m:
                    col_u = m.group(1)
                    if tbl == "users" and col_u.lower() == "roll_number":
                        continue
                    if not any(f'"{col_u}"' in l and "UNIQUE" in l for l in lines):
                        lines.append(f'UNIQUE ("{col_u}")')

        create_stmt = f'CREATE TABLE "{tbl}" (\n  ' + ",\n  ".join(lines) + "\n);"
        p_cursor.execute(create_stmt)

        # Read data from SQLite
        s_cursor.execute(f'SELECT * FROM "{tbl}";')
        rows = s_cursor.fetchall()
        col_names = [c["name"] for c in cols]
        
        if rows:
            cols_quoted = ", ".join(f'"{c}"' for c in col_names)
            placeholders = ", ".join(["%s"] * len(col_names))
            insert_stmt = f'INSERT INTO "{tbl}" ({cols_quoted}) VALUES ({placeholders})'
            
            data = [tuple(r[c] for c in col_names) for r in rows]
            psycopg2.extras.execute_batch(p_cursor, insert_stmt, data, page_size=500)

        # If table has identity sequence, reset it to max(id) + 1
        has_id = any(c["name"] == "id" for c in cols)
        if has_id and rows:
            p_cursor.execute(f'SELECT COALESCE(MAX(id), 0) + 1 FROM "{tbl}";')
            next_id = p_cursor.fetchone()[0]
            try:
                p_cursor.execute("SELECT setval(pg_get_serial_sequence(%s, 'id'), %s, false);", (tbl, next_id))
            except Exception:
                pass

        print(f"  -> Migrated {len(rows)} rows into '{tbl}'.")

    # Migrate indexes from SQLite
    s_cursor.execute("SELECT name, tbl_name, sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL;")
    indexes = s_cursor.fetchall()
    print(f"\n[*] Creating {len(indexes)} database indexes in PostgreSQL...")
    for idx in indexes:
        idx_sql = idx["sql"]
        try:
            p_cursor.execute(idx_sql)
            print(f"  -> Created index {idx['name']}")
        except Exception as e:
            print(f"  -- Note on index {idx['name']}: {e}")

    try:
        p_cursor.execute('CREATE UNIQUE INDEX IF NOT EXISTS users_roll_number_uindex ON users (roll_number) WHERE roll_number IS NOT NULL AND roll_number != \'\';')
        print("  -> Created partial unique index users_roll_number_uindex")
    except Exception as e:
        print(f"  -- Note on users_roll_number_uindex: {e}")

    p_conn.commit()

    # Verification Step
    print("\n=======================================================")
    print("           ROW COUNT PARITY AUDIT (100% CHECK)        ")
    print("=======================================================")
    all_match = True
    for tbl_row in tables:
        tbl = tbl_row["name"]
        s_cursor.execute(f'SELECT COUNT(*) FROM "{tbl}";')
        s_cnt = s_cursor.fetchone()[0]
        p_cursor.execute(f'SELECT COUNT(*) FROM "{tbl}";')
        p_cnt = p_cursor.fetchone()[0]
        status = "✅ MATCH" if s_cnt == p_cnt else "❌ MISMATCH"
        print(f"{tbl:35s}: SQLite={s_cnt:<5} | Postgres={p_cnt:<5} -> {status}")
        if s_cnt != p_cnt:
            all_match = False

    s_conn.close()
    p_conn.close()

    if all_match:
        print("\n[SUCCESS] All 19 tables migrated with 100% data integrity!")
        return 0
    else:
        print("\n[ERROR] Table count mismatch detected!")
        return 1

if __name__ == "__main__":
    sys.exit(migrate())
